version: 3.7
services:
  frps:
    image: mingz2013/frp
    volumes:
    - ./config:/config
    ports:
    - 7000:7000
    command: /frp/frps -c /config/frps.ini
    restart: always
#  frpc:
#    image: mingz2013/frp
#    volumes:
#    - ./config:/config
#    command: /frp/frpc -c /config/frpc.ini
#    restart: always
